format = """
($cmd_duration\n)\
[](#9A348E)\
[$status ](bg:#9A348E)\
[](fg:#9A348E bg:#DA627D)\
$directory[](fg:#DA627D bg:#33658A)\
$git_branch$git_status[](fg:#33658A)
"""

# Disable the blank line at the start of the prompt
add_newline = false



[git_branch]
symbol = ""
style = "bg:#33658A"
format = '[$symbol$branch]($style)'

[git_status]
style = "bg:#33658A"
format = '[$all_status$ahead_behind]($style)'

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true      # Disabled by default

[directory]
style = "bg:#DA627D"
format = "[$path]($style)"
truncation_length = 2
truncation_symbol = "⋯/"

[cmd_duration]
min_time = 1000
style = "bg:#9A348E"
format = 'took [$duration](yellow)'

[status]
disabled = false
success_symbol = "✔"
sigint_symbol = "✘"
not_executable_symbol = "✘"
not_found_symbol = "✘"
signal_symbol = "✘"
map_symbol = true
style = 'bg:#9A348E'
format = '[$symbol]($style)'
symbol = "✘"
